PUT http://localhost:3003/api/blogs/6292825a44517683a782cdd2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphbm5lIiwiaWQiOiI2MjkxMjMxMmNlZjA3YWZlZjVhOWE3NTIiLCJpYXQiOjE2NTM3Njg3NzIsImV4cCI6MTY1Mzc3MjM3Mn0.AVb4gd8_lvlpYFO7aphcvIBSPijGz5YzuwT3R8M1vVM

{
    "title": "Gayblog",
    "author": "Miika",
    "url": "www.fi",
    "likes": 100,
    "userId": "62912312cef07afef5a9a752"
}